general.import = ["~/.config/alacritty/themes/tokyonight/tokyonight_storm.toml"]

[env]
TERM = "xterm-256color"


[font]
normal.family = "JetbrainsMono Nerd Font"
size = 14.0

[window]
decorations = "None"
# startup_mode = "Maximized" # currently broken in GNOME

[window.padding]
x = 0
y = 0

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "tmux attach || tmux -2"]
