import = [
  "~/.config/alacritty/themes/tokyonight/tokyonight_storm.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal.family = "CaskaydiaMono Nerd Font"
size = 10.0

[window]
decorations = "None"
# startup_mode = "Maximized" # currently broken in GNOME
padding.x = 10
padding.y = 10

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
