return {
  "williamboman/mason.nvim",
  opts = {
    auto_install = true,
    ensure_installed = {
      "bicep-lsp",
      "black",
      "codelldb",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "flake8",
      "gopls",
      "lua-language-server",
      "marksman",
      "mypy",
      "pyright",
      "ruff-lsp",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "stylua",
      "taplo",
      "typescript-language-server",
      "yaml-language-server",
      "yamlfmt",
      "yamllint",
    },
  },
}
